Repository easylistpolish/easylistpolish, pull requests merged in 2020-10, with the labels that each got.

#1129 spotradomsko.pl
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1102 rozmiar.com
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1099 irss.pl
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1084 trasa.info
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1085 odleglosci.info
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1086 wyznaczanie-trasy.pl
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1100 mapa.info
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1089 speedwaynews.pl
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1147 EL sorted with FOP.py
  easylistpolish/easylistpolish_adservers_popup.txt
  easylistpolish/easylistpolish_general_block_popup.txt
  easylistpolish/easylistpolish_specific_block.txt
  easylistpolish/easylistpolish_specific_hide.txt
  easylistpolish/easylistpolish_whitelist.txt
  easylistpolish/easylistpolish_whitelist_popup.txt
Labels: sorting

#1151 iloveslubice.pl
  easylistpolish/easylistpolish_specific_block.txt
  easylistpolish/easylistpolish_specific_hide.txt
Labels: to modify

#1222 terazgabin.pl
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1223 terazgostynin.pl
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again

#1224 terazlipno.pl
  easylistpolish/easylistpolish_specific_hide.txt
Labels: check again
